apiVersion: v1
kind: Service
metadata:
  name: nginx-s
  labels:
    name: nginx-s
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  #publicIPs:
   # - 169.44.62.101
  ports:
    # the port that this service should serve on
    - port: 80
      nodePort: 80
  selector:
    name: nginx-s
